@startuml
title SnapShotCreatorシーケンス図

participant ConfigManager

box "SnapShotCreator" #LightBlue
participant Main
participant Worker
end box

activate ConfigManager
activate Main

Main -> Main : StartCapture()
Main -> Main : StopCapture()
ConfigManager -> Main : [A]リクエスト 起動完了確認
Main --> ConfigManager : [A]レスポンス 起動完了確認
loop
    ConfigManager -> Main : [B]リクエスト スナップショット生成
    Main -> Main : StartCapture()
    Main -> Worker : スレッド作成
    activate Worker
    Worker -> Worker : CaptureStills()
    Worker --> Main : 処理結果
    deactivate Worker
    Main -> Main : StopCapture()
    Main --> ConfigManager : [B-a]レスポンス スナップショット生成
end
ConfigManager -> Main : [C]リクエスト サーバ停止
Main -> Main : CancelCapture()
Main --> ConfigManager : [C]レスポンス サーバ停止
deactivate Main

@enduml